home/urls.py
from django.urls import path
from home.views import *

app_name = "home"

urlpatterns = [
    path("Dashboard/", Dashboard, name="Dashboard"),
    path("profile/", Profile, name="Profile"),
    path("licencesearch/", Licence_search, name="Licence_search"),
    path("onlineform/", online_form, name="online_form"),
    path("rules/", Rules, name="Rules"),
    path("genlicence/", genlicence, name="genlicence"),
    path("TrialDateTime/", TrialDateTime, name="TrialDateTime"),

]

login/urls.py
from django.urls import path
from login.views import *

app_name = "login"

urlpatterns = [
    path("login/", Login, name="Login"),
    path("signup/", Signup, name="Signup"),
    path("logoutUser/", logoutUser, name="logoutUser"),

]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('Database/', admin.site.urls),
    path('', include("home.urls", namespace="home")),
    path('', include("login.urls", namespace="login")),
    path('', include("website.urls", namespace="website")),

]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)


admin.site.site_header = "License Management Database"

admin.site.site_title = "Licence"
admin.site.index_title = "Database"

home/models.py
from django.db import models



class examResult(models.Model):
    Passed = "Passed"
    Fail = "Fail"
    Absent = "Absent"
    class_type = (
        (Passed, 'Passed'),
        (Fail, 'Fail'),
        (Absent, 'Absent'),
    )
    applicantid = models.CharField(max_length=255, null=True,blank=True)
    applicantname = models.CharField(max_length=255, null=True,blank=True)
    fathername = models.CharField(max_length=255, null=True,blank=True)
    citizenshipno = models.CharField(max_length=255, null=True,blank=True)
    category = models.CharField(max_length=255, null=True,blank=True)
    status = models.CharField(choices=class_type, max_length=255)         

    def __str__(self):
        return self.applicantname
    
class trialdate(models.Model):
    name = models.ForeignKey(examResult, on_delete=models.CASCADE,null=True, blank=True)
    trialdatetime = models.DateTimeField(null=True, blank=True)
    location = models.CharField(max_length=255, null=True,blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.location
    
    
    
class notices(models.Model):
    notice = models.CharField(max_length=255, null=True,blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.notice   

home/views.py
from django.shortcuts import redirect, render,reverse
from django.http import HttpResponse, HttpResponseRedirect
from home.models import *
from django.contrib import messages
from website.models import *
from django.contrib.auth.decorators import login_required

# Create your models here.
@login_required(login_url='login:Login')
def Dashboard(request):
    data = OnlineLicenceForm.objects.all().count()
    data2 = examResult.objects.all().count()
    data3 = notices.objects.all().count()
    
    
    conte = {
        "data":data,
        "data2":data2,
        "data3":data3,
    }

    return render(request, "Dashboard.html", conte)

@login_required(login_url='login:Login')
def Profile(request):
    return render(request, "profile.html")



@login_required(login_url='login:Login')
def Licence_search(request):
    if request.method =='POST':
            exam = examResult()
            applicantid = request.POST.get('applicantid')
            applicantname = request.POST.get('applicantname')
            fathername = request.POST.get('fathername')
            citizenshipno = request.POST.get('citizenshipno')
            category = request.POST.get('category')
            status = request.POST.get('status')
            exam.applicantid = applicantid
            exam.applicantname = applicantname
            exam.fathername = fathername
            exam.citizenshipno = citizenshipno
            exam.category = category
            exam.status = status
            exam.save()
            messages.success(request, 'Contact request submitted successfully.')
            return redirect('/Dashboard')  
    return render(request, "licencesearch.html")


@login_required(login_url='login:Login')
def online_form(request):
    data = OnlineLicenceForm.objects.all() 
    context = {
        "data": data,      
        }
    return render(request, "onlineform.html", context)


@login_required(login_url='login:Login')
def Rules(request):
    if request.method == 'POST':
        rule = notices()
        notice = request.POST.get('notice')
        rule.notice = notice
        rule.save()
        return redirect('/Dashboard')  
        
    return render(request, "rules.html")






@login_required(login_url='login:Login')
def genlicence(request):
    return render(request, "LicenceGenerate.html")



@login_required(login_url='login:Login')
def TrialDateTime(request):
    if request.method == 'POST':
        tri = trialdate()
        trialdatetime = request.POST.get('trialdatetime')
        location = request.POST.get('location')
        tri.trialdatetime = trialdatetime
        tri.location = location
        tri.save()
        return redirect('/Dashboard')  
    return render(request, "trialdatetimeh.html")

home/templates/LicenceGenerate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Creating PDF from HTML</title>
    <link rel="stylesheet" href="style.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js" integrity="sha512-GsLlZN/3F2ErC5ifS5QtgpiJtWd43JWSuIgh7mbzZ8zBps+dvLusV+eNQATqgA/HdeKFVgA5v3S/cIrLF7QnIg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="html2pdf.bundle.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.8.0/html2pdf.bundle.min.js"></script>


    <style>
        h1{
            text-align: right;
        }
        .tab{
            margin-left: 30px;
            margin-top: 10px;
        }
        .tab2{
            margin-left: 30px;
        }
        .img1{
            height: 90px;
            border-radius: 30px;
        }
        .img2{
            height: 90px;
            width: 100px;
        }
        .img3{
            height: 60px;
        }
        .gov{
            color: red;
            text-align: center;
            text-transform: uppercase;
            font-size: 28px;
            margin-left: 29px;

        }
        .gov2{
            text-align: center;
            text-transform: uppercase;
            font-size: 11px;
            margin-left: 90px;
        }
        .aq{
            width: 150px;
        
        }
        .btn{
          border: 1px solid red;
          padding: 5px;
          margin: 5px;
          background-color: rgb(211, 240, 198);
          text-decoration: none;
          text-align: center;
        }
        .navbar{
          text-align: center;
          font-size: 28px;
        }
    </style>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.4/jspdf.debug.js" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.4/jspdf.min.js" ></script>
</head>
<body>
<!-- Just an image -->
<nav class="navbar navbar-light bg-light">
  <a class="btn" class="navbar-brand" href="{% url 'home:Dashboard' %}">
    Dashboard
  </a>
</nav>



    <div  class="container-fluid">
        <div class="container">
            <div class="part1">
                <fieldset>
                    <legend>Licence Details</legend>
                    Full Name: <input type="text" id="name"> <br/>
                    Licence No: <input type="text" id="licenceno">
                    Father Name: <input type="text" id="fathername">
                    Blood Group: <input type="text" id="bloodgroup">
                    Address: <input type="text" id="address">
                    Date of birth: <input type="date" id="dateofbirth">
                    Citizinship No: <input type="text" id="citizinshipno">
                    Contact No: <input type="text" id="contactno">
                    Category: <input type="text" id="category">
                    D.O.I: <input type="date" id="doi">
                    D.O.E: <input type="date" id="doe">
                </fieldset>
            </div>
        </div>
    
        <div id="mypdf">

        <div class="container">

            <fieldset>
                <div  style="border: 1px solid red; width:700px; height:60vh; background-image:linear-gradient(90deg, rgba(227, 227, 227,1) 20.328125854333244%,rgba(227, 226, 227,1) 20.328125854333244%,rgba(227, 191, 245,1) 80.32812823851904%)
                ;">
                    <table class="tab" style="width: 700px;">
                        <tr>
                            <td style="width:150px;" >
                                <img class="img1" src="/static/assets/images/download.jpeg" alt="logo">
                            </td>
                            <td class="">
                                <span class="gov"> Government of nepal </span> <br>
                                <span class="gov2"> Non professional driving license </span> <br>
                          </td>
                          <td  style="width:150px;" >
                            <img style="padding:5px;" class="img2" src="/static/assets/images/Flags-Nepal.jpeg">
                        </td>
                        </tr>
                    </table>

                    <table  class="tab2" style="width: 700px;">
                        <tr>
                            <td  class="aq">
                                <h3  style="margin-top: -10px;">L.NO: <span style="font-size: 12px; font-weight:500;" id="licenceno2"></span></h3> <br>
                                <h3  style="margin-top: -30px;">B.G: <span style="font-size: 12px; font-weight:500;" id="bloodgroup2"></span></h3> <br>
                                <img style="padding:5px; margin-top:-37px;" class="img3" src="/static/assets/images/Capture.jpeg" alt="">
                                <h3  style="margin-top: 10px;">D.O.I: <span style="font-size: 12px; font-weight:500;" id="doi2"></span></h3> <br>
                                <h3  style="margin-top: -30px;">D.O.E: <span style="font-size: 12px; font-weight:500;" id="doe2"></span></h3> <br>
                            </td>
                            <td class="nam">
                                <h3 style="margin-left: 35px;">Name: <span style="font-size: 12px; font-weight:500;" id="name2"></span> </h3><br>
                                <h3 style="margin-left: 35px; margin-top: -25px;">Address: <span style="font-size: 12px; font-weight:500;" id="address2"></span></h3> <br>
                                <h3 style="margin-left: 35px; margin-top: -25px;">F.Name: <span style="font-size: 12px; font-weight:500;" id="fathername2"></span></h3> <br>
                                <h3 style="margin-left: 35px; margin-top: -25px;">D.O.B: <span style="font-size: 12px; font-weight:500;" id="dateofbirth2"></span></h3> <br>
                                <h3 style="margin-left: 35px; margin-top: -25px;">Citizenship No: <span style="font-size: 12px; font-weight:500;" id="citizinshipno2"></span></h3> <br>
                                <h3 style="margin-left: 35px; margin-top: -25px;">Phone No: <span style="font-size: 12px; font-weight:500;" id="contactno2"></span></h3> <br>
                            </td>
                            <td style="width:150px;" >
                                <img class="img2" style=" border:1px solid red; margin-top: -55px;" src="/static/assets/images/no.jpeg" alt="">
                                <h3  style="margin-top: 1px;">Category: <span style="font-size: 12px; font-weight:500;" id="category2"></span></h3> <br>

                            </td>
                        </tr>
                    </table>
                    <table style="width: 700px;">
                        <tr>
                            <td style="text-align: center;">
                                <input  style="height: 40px; text-align:center;  " type="text" class="form-control" id="exampleInputEmail1"><br> 
                                <label for="exampleInputEmail1">Issued By</label>  
                            </td>
                            <td style="text-align: center;">                              
                                <input style="height: 40px; text-align:center; " type="text" class="form-control" id="exampleInputEmail1"> <br>
                                <label for="exampleInputEmail1">Signature</label>
                            </td>
                        </tr>
                    </table>
                </div>
            </fieldset>
                
        </div>
    </div>
        
</div>
    <button onclick="toPdf()">download</button>
    <script>
        function toPdf(){
            var element = document.getElementById("mypdf");
        
           html2pdf(element, {
               margin:       10,
               filename:     'Citizenship.pdf',
               image:        { type: 'jpeg' , quality: 0.98 },
               html2canvas:  { scale: 2, logging: true, dpi: 192, letterRendering: true },
               jsPDF:        { unit: 'mm', format: 'a4', orientation: 'portrait' }
             });
             html2pdf().from(element).save();
        }


var name = "", licenceno="", fathername="", bloodgroup="", address="", dateofbirth="", citizinshipno="", contactno="", category="", doi="", doe="";
document.getElementById("name").addEventListener("keyup",function(){
    // name = document.getElementById("name").value;
    
    document.getElementById("name2").innerHTML=this.value;
});

document.getElementById("licenceno").addEventListener("keyup",function(){
    // name = document.getElementById("name").value;
    
    document.getElementById("licenceno2").innerHTML=this.value;
});
document.getElementById("fathername").addEventListener("keyup",function(){
    // name = document.getElementById("name").value;
    document.getElementById("fathername2").innerHTML=this.value;
});
document.getElementById("bloodgroup").addEventListener("keyup",function(){
    // name = document.getElementById("name").value;
    
    document.getElementById("bloodgroup2").innerHTML=this.value;
});
document.getElementById("address").addEventListener("keyup",function(){
    // name = document.getElementById("name").value;
    
    document.getElementById("address2").innerHTML=this.value;
});
document.getElementById("dateofbirth").addEventListener("keyup",function(){
    // name = document.getElementById("name").value;
    
    document.getElementById("dateofbirth2").innerHTML=this.value;
});
document.getElementById("citizinshipno").addEventListener("keyup",function(){
    // name = document.getElementById("name").value;
    
    document.getElementById("citizinshipno2").innerHTML=this.value;
});
document.getElementById("contactno").addEventListener("keyup",function(){
    // name = document.getElementById("name").value;
    
    document.getElementById("contactno2").innerHTML=this.value;
});
document.getElementById("category").addEventListener("keyup",function(){
    // name = document.getElementById("name").value;
    
    document.getElementById("category2").innerHTML=this.value;
});
document.getElementById("doi").addEventListener("keyup",function(){
    // name = document.getElementById("name").value;
    
    document.getElementById("doi2").innerHTML=this.value;
});
document.getElementById("doe").addEventListener("keyup",function(){
    // name = document.getElementById("name").value;
    
    document.getElementById("doe2").innerHTML=this.value;
});


    </script>
</body>
</html>

<!--

HTML + CSS -> PNG (html2canvas)
PNG -> Add to PDF (jsPDF)
Download PDF (jsPDF)

-->

home/templates/onlineform.html
{% extends 'home/Homebase.html' %} {% load static %} {% block Dashboard %}
<div id="main-wrapper">
  <div class="nav-header">
    <a href="{% url 'home:Dashboard' %}" class="brand-logo">
      <svg
        class="logo-abbr"
        width="55"
        height="55"
        viewbox="0 0 55 55"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
      >
        <path
          fill-rule="evenodd"
          clip-rule="evenodd"
          d="M27.5 0C12.3122 0 0 12.3122 0 27.5C0 42.6878 12.3122 55 27.5 55C42.6878 55 55 42.6878 55 27.5C55 12.3122 42.6878 0 27.5 0ZM28.0092 46H19L19.0001 34.9784L19 27.5803V24.4779C19 14.3752 24.0922 10 35.3733 10V17.5571C29.8894 17.5571 28.0092 19.4663 28.0092 24.4779V27.5803H36V34.9784H28.0092V46Z"
          fill="url(#paint0_linear)"
        ></path>
        <defs></defs>
      </svg>
    </a>
    <div class="nav-control">
      <div class="hamburger">
        <span class="line"></span><span class="line"></span
        ><span class="line"></span>
      </div>
    </div>
  </div>

  <div class="chatbox">
    <div class="chatbox-close"></div>
    <div class="custom-tab-1">
      <ul class="nav nav-tabs">
        <li class="nav-item">
          <a class="nav-link" data-bs-toggle="tab" href="#notes">Notes</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" data-bs-toggle="tab" href="#alerts">Alerts</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" data-bs-toggle="tab" href="#chat">Chat</a>
        </li>
      </ul>
    </div>
  </div>

  <div class="header border-bottom">
    <div class="header-content">
      <nav class="navbar navbar-expand">
        <div class="collapse navbar-collapse justify-content-between">
          <div class="header-left">
            <div class="dashboard_bar">Licence Form</div>
          </div>
          <ul class="navbar-nav header-right">
            <li class="nav-item d-flex align-items-center">
              <div class="input-group search-area">
                <input
                  type="text"
                  class="form-control"
                  placeholder="Search here..."
                />
                <span class="input-group-text"
                  ><a href="javascript:void(0)"
                    ><i class="flaticon-381-search-2"></i></a
                ></span>
              </div>
            </li>
            <li class="nav-item dropdown notification_dropdown">
              <a class="nav-link" href="javascript:void(0);">
                <svg
                  width="28"
                  height="28"
                  viewbox="0 0 28 28"
                  fill="none"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    d="M26.7727 10.8757C26.7043 10.6719 26.581 10.4909 26.4163 10.3528C26.2516 10.2146 26.0519 10.1247 25.8393 10.0929L18.3937 8.95535L15.0523 1.83869C14.9581 1.63826 14.8088 1.46879 14.6218 1.35008C14.4349 1.23137 14.218 1.16833 13.9965 1.16833C13.775 1.16833 13.5581 1.23137 13.3712 1.35008C13.1842 1.46879 13.0349 1.63826 12.9407 1.83869L9.59934 8.95535L2.15367 10.0929C1.9416 10.1252 1.74254 10.2154 1.57839 10.3535C1.41423 10.4916 1.29133 10.6723 1.22321 10.8757C1.15508 11.0791 1.14436 11.2974 1.19222 11.5065C1.24008 11.7156 1.34468 11.9075 1.49451 12.061L6.92067 17.6167L5.63734 25.4777C5.60232 25.6934 5.6286 25.9147 5.7132 26.1162C5.79779 26.3177 5.93729 26.4914 6.1158 26.6175C6.29432 26.7436 6.50466 26.817 6.72287 26.8294C6.94108 26.8418 7.15838 26.7926 7.35001 26.6875L14 23.0149L20.65 26.6875C20.8416 26.7935 21.0592 26.8434 21.2779 26.8316C21.4965 26.8197 21.7075 26.7466 21.8865 26.6205C22.0655 26.4944 22.2055 26.3204 22.2903 26.1186C22.3751 25.9167 22.4014 25.695 22.3662 25.4789L21.0828 17.6179L26.5055 12.061C26.6546 11.9071 26.7585 11.715 26.8056 11.5059C26.8527 11.2968 26.8413 11.0787 26.7727 10.8757Z"
                    fill="#717579"
                  ></path>
                </svg>
                <span class="badge light text-white bg-secondary rounded-circle"
                  >15</span
                >
              </a>
            </li>
            <li class="nav-item dropdown notification_dropdown">
              <a
                class="nav-link"
                href="javascript:void(0);"
                role="button"
                data-bs-toggle="dropdown"
              >
                <svg
                  width="28"
                  height="28"
                  viewbox="0 0 28 28"
                  fill="none"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    d="M23.3333 19.8333H23.1187C23.2568 19.4597 23.3295 19.065 23.3333 18.6666V12.8333C23.3294 10.7663 22.6402 8.75902 21.3735 7.12565C20.1068 5.49228 18.3343 4.32508 16.3333 3.80679V3.49996C16.3333 2.88112 16.0875 2.28763 15.6499 1.85004C15.2123 1.41246 14.6188 1.16663 14 1.16663C13.3812 1.16663 12.7877 1.41246 12.3501 1.85004C11.9125 2.28763 11.6667 2.88112 11.6667 3.49996V3.80679C9.66574 4.32508 7.89317 5.49228 6.6265 7.12565C5.35983 8.75902 4.67058 10.7663 4.66667 12.8333V18.6666C4.67053 19.065 4.74316 19.4597 4.88133 19.8333H4.66667C4.35725 19.8333 4.0605 19.9562 3.84171 20.175C3.62292 20.3938 3.5 20.6905 3.5 21C3.5 21.3094 3.62292 21.6061 3.84171 21.8249C4.0605 22.0437 4.35725 22.1666 4.66667 22.1666H23.3333C23.6428 22.1666 23.9395 22.0437 24.1583 21.8249C24.3771 21.6061 24.5 21.3094 24.5 21C24.5 20.6905 24.3771 20.3938 24.1583 20.175C23.9395 19.9562 23.6428 19.8333 23.3333 19.8333Z"
                    fill="#717579"
                  ></path>
                  <path
                    d="M9.9819 24.5C10.3863 25.2088 10.971 25.7981 11.6766 26.2079C12.3823 26.6178 13.1838 26.8337 13.9999 26.8337C14.816 26.8337 15.6175 26.6178 16.3232 26.2079C17.0288 25.7981 17.6135 25.2088 18.0179 24.5H9.9819Z"
                    fill="#717579"
                  ></path>
                </svg>
                <span class="badge light text-white bg-warning rounded-circle"
                  >12</span
                >
              </a>
            </li>
            <li class="nav-item dropdown notification_dropdown">
              <a class="nav-link bell-link" href="javascript:void(0);">
                <svg
                  width="28"
                  height="28"
                  viewbox="0 0 28 28"
                  fill="none"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    d="M27.076 6.24662C26.962 5.48439 26.5787 4.78822 25.9955 4.28434C25.4123 3.78045 24.6679 3.50219 23.8971 3.5H4.10289C3.33217 3.50219 2.58775 3.78045 2.00456 4.28434C1.42137 4.78822 1.03803 5.48439 0.924011 6.24662L14 14.7079L27.076 6.24662Z"
                    fill="#717579"
                  ></path>
                  <path
                    d="M14.4751 16.485C14.3336 16.5765 14.1686 16.6252 14 16.6252C13.8314 16.6252 13.6664 16.5765 13.5249 16.485L0.875 8.30025V21.2721C0.875926 22.1279 1.2163 22.9484 1.82145 23.5536C2.42659 24.1587 3.24707 24.4991 4.10288 24.5H23.8971C24.7529 24.4991 25.5734 24.1587 26.1786 23.5536C26.7837 22.9484 27.1241 22.1279 27.125 21.2721V8.29938L14.4751 16.485Z"
                    fill="#717579"
                  ></path>
                </svg>
                <span class="badge light text-white bg-danger rounded-circle"
                  >16</span
                >
              </a>
            </li>
            <li class="nav-item dropdown header-profile">
              <a
                class="nav-link"
                href="javascript:void(0);"
                role="button"
                data-bs-toggle="dropdown"
              >
                <img src="/static/images/user.jpg" width="56" alt="" />
              </a>
              <div class="dropdown-menu dropdown-menu-end">
                <a
                  href="{% url 'home:Profile' %}"
                  class="dropdown-item ai-icon"
                >
                  <svg
                    id="icon-user1"
                    xmlns="http://www.w3.org/2000/svg"
                    class="text-primary"
                    width="18"
                    height="18"
                    viewbox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                  >
                    <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path>
                    <circle cx="12" cy="7" r="4"></circle>
                  </svg>
                  <span class="ms-2">Profile </span>
                </a>
                <a href="email-inbox.html" class="dropdown-item ai-icon">
                  <svg
                    id="icon-inbox"
                    xmlns="http://www.w3.org/2000/svg"
                    class="text-success"
                    width="18"
                    height="18"
                    viewbox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                  >
                    <path
                      d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"
                    ></path>
                    <polyline points="22,6 12,13 2,6"></polyline>
                  </svg>
                  <span class="ms-2">Inbox </span>
                </a>
                <a href="{% url 'login:logoutUser' %}" class="dropdown-item ai-icon">
                  <svg
                    id="icon-logout"
                    xmlns="http://www.w3.org/2000/svg"
                    class="text-danger"
                    width="18"
                    height="18"
                    viewbox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                  >
                    <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"></path>
                    <polyline points="16 17 21 12 16 7"></polyline>
                    <line x1="21" y1="12" x2="9" y2="12"></line>
                  </svg>
                  <span class="ms-2">Logout </span>
                </a>
              </div>
            </li>
          </ul>
        </div>
      </nav>
    </div>
  </div>

 
  <div class="dlabnav">
    <div class="dlabnav-scroll">
      <ul class="metismenu" id="menu">
        <li>
          <a href="{% url 'home:Dashboard' %}" aria-expanded="false">
            <i class="fas fa-home"></i>
            <span class="nav-text">Dashboard</span>
          </a>
        </li>

        <li>
          <a href="{% url 'home:online_form' %}" aria-expanded="false">
            <i class="fas fa-pen"></i>
            <span class="nav-text">Online License form </span>
          </a>
        </li>
        <li>
          <a href="{% url 'home:Licence_search' %}" aria-expanded="false">
            <i class="fas fa-search"></i>
            <span class="nav-text">Post Exam Result</span>
          </a>
        </li>
        <li>
          <a href="{% url 'home:Rules' %}" aria-expanded="false">
            <i class="fas fa-address-book"></i>
            <span class="nav-text">Notices </span>
          </a>
        </li>
        <li>
          <a href="{% url 'home:TrialDateTime' %}" aria-expanded="false">
            <i class="fas fa-certificate"></i>
            <span class="nav-text">Trial Date </span>
          </a>
        </li>
        <li>
          <a href="{% url 'home:genlicence' %}" aria-expanded="false">
            <i class="fas fa-brain"></i>
            <span class="nav-text">Licence </span>
          </a>
        </li>
        <li>
          <a href="/Database" aria-expanded="false">
            
            <i class="fas fa-blog"></i>
            <span class="nav-text">Database </span>
          </a>
        </li>
		  <li>
			<a href="{% url 'login:logoutUser' %}" aria-expanded="false">
			  <i class="fas fa-arrow-left"></i>
			  <span class="nav-text">Logout </span>
			</a>
		  </li>
      </ul>
    </div>
  </div>

  <div class="content-body">
    <!-- row -->
    <div class="container-fluid">
      <div class="row">
        <div class="col-xl-12">
          <table class="table table-striped table-bordered table-hover" style="width: 50px; z-index:1;">
            <thead class="thead-dark">
              <tr>
                <th scope="col">#</th>
                <th scope="col">Blood Group</th>
                <th scope="col">Passport No</th>
                <th scope="col">Citizenship No</th>
                <th scope="col">Date Of Birth</th>
                <th scope="col">First Name</th>
                <th scope="col">Middle Name</th>
                <th scope="col">Last Name</th>
                <th scope="col">license Catagory</th>
                <th scope="col">Document Type</th>


              </tr>
            </thead>
            <tbody>
              {% for i in data %}
              <tr>
                <td>{{forloop.counter}}</td>
                <td>{{i.bloodgroup}}</td>
                <td>{{i.passportno}}</td>
                <td>{{i.citizenshipno}}</td>
                <td>{{i.dateofbirth}}</td>
                <td>{{i.firstname}}</td>
                <td>{{i.middlename}}</td>
                <td>{{i.lastname}}</td>
                <td>{{i.licensecatagory}}</td>
                <td>{{i.documenttype}}</td>



              </tr>
            </tbody>
            {% endfor %}
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}