home/urls.py
from django.urls import path
from home.views import *

app_name = "home"

urlpatterns = [
    path("Dashboard/", Dashboard, name="Dashboard"),
    path("profile/", Profile, name="Profile"),
    path("licencesearch/", Licence_search, name="Licence_search"),
    path("onlineform/", online_form, name="online_form"),
    path("rules/", Rules, name="Rules"),
    path("genlicence/", genlicence, name="genlicence"),
    path("TrialDateTime/", TrialDateTime, name="TrialDateTime"),

]

login/urls.py
from django.urls import path
from login.views import *

app_name = "login"

urlpatterns = [
    path("login/", Login, name="Login"),
    path("signup/", Signup, name="Signup"),
    path("logoutUser/", logoutUser, name="logoutUser"),

]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('Database/', admin.site.urls),
    path('', include("home.urls", namespace="home")),
    path('', include("login.urls", namespace="login")),
    path('', include("website.urls", namespace="website")),

]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)


admin.site.site_header = "License Management Database"

admin.site.site_title = "Licence"
admin.site.index_title = "Database"

login/models.py
from django.db import models

# Create your models here.

login/views.py
from django.shortcuts import redirect, render,reverse
from django.http import HttpResponse, HttpResponseRedirect


from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from login.decorators import *
# Create your models here.


def Signup(request):
    return render(request, "LoginSignup.html")





@unauthenticated_user
def Login(request):	
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
            
        user = authenticate(request, username=username, password=password) 
        if user is not None:
            login(request, user)
            return redirect('home:Dashboard')
        else:
            messages.info(request, 'Username OR password is incorrect')
    
    context = {} 
    return render(request, "loginpage.html", context)
 
 
 
def logoutUser(request):
	logout(request)
	return redirect('login:Login')

login/templates/LoginSignup.html
{% extends 'Loginbase.html' %} 

{% load static %}



{% block signup %}



<body class="vh-100">
    <div class="authincation h-100">
        <div class="container h-100">
            <div class="row justify-content-center h-100 align-items-center">
                <div class="col-md-6">
                    <div class="authincation-content">
                        <div class="row no-gutters">
                            <div class="col-xl-12">
                                <div class="auth-form">
									<div class="text-center mb-3">
										<a href=""><img src="images/logo-full.png" alt=""></a>
									</div>
                                    <h4 class="text-center mb-4">Sign up your account</h4>


                                    <form action="" method="POST" autocomplete="off">
                                        {% csrf_token %}
                                        <div class="mb-3">
                                            <label class="mb-1"><strong>Username</strong></label>
                                            <input type="text" class="form-control" placeholder="username">
                                        </div>
                                        <div class="mb-3">
                                            <label class="mb-1"><strong>Email</strong></label>
                                            <input type="email" class="form-control" placeholder="hello@example.com">
                                        </div>
                                        <div class="mb-3">
                                            <label class="mb-1"><strong>Password</strong></label>
                                            <input type="password" class="form-control" placeholder="Password">
                                        </div>
                                        <div class="text-center mt-4">
                                            <button type="submit" class="btn btn-primary btn-block">Sign me up</button>
                                        </div>
                                    </form>
                                    <div class="new-account mt-3">
                                        <p>Already have an account? <a class="text-primary" href="{% url 'login:Login' %}">Sign in</a></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

login/templates/loginpage.html
{% extends 'Loginbase.html' %} 

{% load static %}



{% block Loginpage %}


<body class="vh-100">
    <div class="authincation h-100">
        <div class="container h-100">
            <div class="row justify-content-center h-100 align-items-center">
                <div class="col-md-6">
                    <div class="authincation-content">
                        <div class="row no-gutters">
                            <div class="col-xl-12">
                                <div class="auth-form">
									<div class="text-center mb-3">
										<a href="/"><img src="/static/images/circle-hunt.png" alt=""></a>
									</div>
                                    <h4 class="text-center mb-4">Sign in your account</h4>


                                    <form action="" method="POST" autocomplete="off">
                                        {% csrf_token %}
                                        <div class="mb-3">
                                            <label class="mb-1"><strong>User Name</strong></label>
                                            <input type="text" name="username" class="form-control" placeholder="Enter You username">
                                        </div>
                                        <div class="mb-3">
                                            <label class="mb-1"><strong>Password</strong></label>
                                            <input type="password" name="password" class="form-control" placeholder="Enter your password">
                                        </div>
                                        <div class="row d-flex justify-content-between mt-4 mb-2">
                                            <div class="mb-3">
                                               <div class="form-check custom-checkbox ms-1">
													<input type="checkbox" class="form-check-input" id="basic_checkbox_1">
													<label class="form-check-label" for="basic_checkbox_1">Remember my preference</label>
												</div>
                                            </div>
                                            <div class="mb-3">
                                                <a href="">Forgot Password?</a>
                                            </div>
                                        </div>
                                        <div class="text-center">
                                            <button type="submit" class="btn btn-primary btn-block">Sign Me In</button>
                                        </div>
                                    </form>
                                    <div class="new-account mt-3">
                                        <p>Don't have an account? <a class="text-primary" href="{% url 'login:Signup' %}">Sign up</a></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>




{% endblock %}