home/urls.py
from django.urls import path
from home.views import *

app_name = "home"

urlpatterns = [
    path("Dashboard/", Dashboard, name="Dashboard"),
    path("profile/", Profile, name="Profile"),
    path("licencesearch/", Licence_search, name="Licence_search"),
    path("onlineform/", online_form, name="online_form"),
    path("rules/", Rules, name="Rules"),
    path("genlicence/", genlicence, name="genlicence"),
    path("TrialDateTime/", TrialDateTime, name="TrialDateTime"),

]

login/urls.py
from django.urls import path
from login.views import *

app_name = "login"

urlpatterns = [
    path("login/", Login, name="Login"),
    path("signup/", Signup, name="Signup"),
    path("logoutUser/", logoutUser, name="logoutUser"),

]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('Database/', admin.site.urls),
    path('', include("home.urls", namespace="home")),
    path('', include("login.urls", namespace="login")),
    path('', include("website.urls", namespace="website")),

]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)


admin.site.site_header = "License Management Database"

admin.site.site_title = "Licence"
admin.site.index_title = "Database"

website/urls.py
from django.urls import path
from website.views import *

app_name = "website"

urlpatterns = [
    path('', Websiteindex, name="Websiteindex" ),
    path('Online_Form_Fill/', Online_Form_Fill, name="Online_Form_Fill" ),
    path('ExamResult/', ExamResult, name="ExamResult" ),
    path('noticesnews/', noticesnews, name="noticesnews" ),
    path('LocationOFTrial/', LocationOFTrial, name="LocationOFTrial" ),

]

website/models.py
from django.db import models

# Create your models here.
class OnlineLicenceForm(models.Model):
    bloodgroup = models.CharField(max_length=255, null=True,blank=True)
    citizenshipissuedistrict = models.CharField(max_length=255, null=True,blank=True)
    passportno = models.TextField(max_length=255, null=True,blank=True)
    citizenshipno = models.CharField(max_length=255, null=True,blank=True)
    dateofbirth = models.DateField(max_length=255, null=True,blank=True)
    firstname = models.CharField(max_length=255, null=True,blank=True)
    middlename = models.CharField(max_length=255, null=True,blank=True)
    lastname = models.CharField(max_length=255, null=True,blank=True)
    relationship = models.CharField(max_length=255, null=True,blank=True)
    occupation = models.CharField(max_length=255, null=True,blank=True)
    address = models.CharField(max_length=255, null=True,blank=True)
    zone = models.CharField(max_length=255, null=True,blank=True)
    email = models.EmailField(max_length=255, null=True,blank=True)
    contactno = models.BigIntegerField(null=True,blank=True)
    officecontactno = models.BigIntegerField(null=True,blank=True)
    licensecatagory = models.CharField(max_length=255, null=True,blank=True)
    uploaddocument = models.ImageField(upload_to="upload/image", null=True, blank=True)
    documenttype = models.CharField(max_length=255, null=True,blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.firstname
    
    class Meta:
            db_table = 'Online Forms'
            
            

    

website/views.py
from django.shortcuts import redirect, render,reverse
from django.http import HttpResponse, HttpResponseRedirect
from website.models import *
from django.contrib import messages
from home.models import *


# Create your models here.
def Websiteindex(request):
    data = notices.objects.all()
    contex = {
        "data":data,
    }
    return render(request, "weblic.html", contex)

def noticesnews(request):
    data = notices.objects.all()
    contex = {
        "data":data,
    }
    return render(request, "notices.html", contex)


def Online_Form_Fill(request):
    data = OnlineLicenceForm.objects.all().count()
    if request.method =='POST':
            onform = OnlineLicenceForm()
            bloodgroup = request.POST.get('bloodgroup')
            citizenshipissuedistrict = request.POST.get('citizenshipissuedistrict')
            passportno = request.POST.get('passportno')
            citizenshipno = request.POST.get('citizenshipno')
            dateofbirth = request.POST.get('dateofbirth')
            firstname = request.POST.get('firstname')
            middlename = request.POST.get('middlename')
            lastname = request.POST.get('lastname')
            relationship = request.POST.get('relationship')
            occupation = request.POST.get('occupation')
            address = request.POST.get('address')
            zone = request.POST.get('zone')
            email = request.POST.get('email')
            contactno = request.POST.get('contactno')
            officecontactno = request.POST.get('officecontactno')
            licensecatagory = request.POST.get('licensecatagory')
            uploaddocument = request.POST.get('uploaddocument')
            documenttype = request.POST.get('documenttype')
            onform.bloodgroup = bloodgroup
            onform.citizenshipissuedistrict = citizenshipissuedistrict
            onform.passportno = passportno
            onform.citizenshipno = citizenshipno
            onform.dateofbirth = dateofbirth
            onform.firstname = firstname
            onform.middlename = middlename
            onform.lastname = lastname
            onform.relationship = relationship
            onform.occupation = occupation
            onform.address = address
            onform.zone = zone
            onform.email = email
            onform.contactno = contactno
            onform.officecontactno = officecontactno
            onform.licensecatagory = licensecatagory
            onform.uploaddocument = uploaddocument
            onform.documenttype = documenttype
            onform.save()
            messages.success(request, 'Contact request submitted successfully.')
            return redirect('/')
    context = {
        'data':data,
    }
    return render(request, "fillonlineform.html", context)




def ExamResult(request):
    data = examResult.objects.all()
    context = {
        "data":data,
               }
      
    return render(request, "examresult.html", context)


def LocationOFTrial(request):
    data = trialdate.objects.all()
    context = {
        "data":data,
               }
      
    return render(request, "Trialdatetime.html", context)

website/templates/Trialdatetime.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Licence Management System </title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-primary">
      <div class="container-fluid">
        <a class="navbar-brand" href="">Website</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'website:Websiteindex' %}"
                >Home</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'website:Online_Form_Fill' %}"
                >Fill Form</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'website:ExamResult' %}"
                >Exam Result</a
              >
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'website:noticesnews' %}"
                  >Notices</a
                >
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'website:LocationOFTrial' %}"
                  >Trial Date</a
                >
              </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login:Login' %}"
                >Login</a
              >
            </li>
          </ul>

        </div>
      </div>
    </nav>

    <div class="container">
    <table class="table" style="padding: 10px; margin:10px;">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Applicant Name</th>
            <th scope="col">Applicant Trial Date & Time</th>
            <th scope="col">Trial Location</th>
          </tr>
        </thead>

        <tbody>
        {% for i in data %}
          <tr>
            <th scope="row">{{forloop.counter}}</th>
            <td>{{i.name}}</td>
            <td>{{i.trialdatetime}}</td>
            <td>{{i.location}}</td>
          </tr>
        </tbody>
        {% endfor %}
      </table>
    </div>




      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>


  </body>
</html>

website/templates/examresult.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Licence Management System </title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-primary">
      <div class="container-fluid">
        <a class="navbar-brand" href="">Website</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'website:Websiteindex' %}"
                >Home</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'website:Online_Form_Fill' %}"
                >Fill Form</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'website:ExamResult' %}"
                >Exam Result</a
              >
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'website:noticesnews' %}"
                  >Notices</a
                >
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'website:LocationOFTrial' %}"
                  >Trial Date</a
                >
              </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login:Login' %}"
                >Login</a
              >
            </li>
          </ul>

        </div>
      </div>
    </nav>

    <div class="container">
    <table class="table" style="padding: 10px; margin:10px;">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Applicant id</th>
            <th scope="col">Applicant Name</th>
            <th scope="col">Father Name</th>
            <th scope="col">Citizenship</th>
            <th scope="col">Category</th>
            <th scope="col">Status</th>
          </tr>
        </thead>

        <tbody>
        {% for i in data %}
          <tr>
            <th scope="row">{{forloop.counter}}</th>
            <td>{{i.applicantid}}</td>
            <td>{{i.applicantname}}</td>
            <td>{{i.fathername}}</td>
            <td>{{i.citizenshipno}}</td>
            <td>{{i.category}}</td>
            <td>{{i.status}}</td>
          </tr>
        </tbody>
        {% endfor %}
      </table>
    </div>




      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>


  </body>
</html>

website/templates/notices.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Licence Management System </title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-primary">
      <div class="container-fluid">
        <a class="navbar-brand" href="">Website</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'website:Websiteindex' %}"
                >Home</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'website:Online_Form_Fill' %}"
                >Fill Form</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'website:ExamResult' %}"
                >Exam Result</a
              >
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'website:noticesnews' %}"
                  >Notices</a
                >
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'website:LocationOFTrial' %}"
                  >Trial Date</a
                >
              </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login:Login' %}"
                >Login</a
              >
            </li>
          </ul>

        </div>
      </div>
    </nav>

    <div class="container" style="background-color: rgb(243, 237, 233);">
      {% for i in data %}
      <marquee behavior="" direction="">
        <div >
        <h4 style="color: rgb(72, 0, 255);"><li>{{i.notice}}</li></h4>
    </div>
      </marquee>
      {% endfor %}
    </div>




      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>


  </body>
</html>

website/templates/weblic.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Licence Management System </title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-primary">
      <div class="container-fluid">
        <a class="navbar-brand" href="">Website</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'website:Websiteindex' %}"
                >Home</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'website:Online_Form_Fill' %}"
                >Fill Form</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'website:ExamResult' %}"
                >Exam Result</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'website:noticesnews' %}"
                >Notices</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login:Login' %}"
                >Login</a
              >
            </li>
          </ul>

        </div>
      </div>
    </nav> <br>



<div class="container">
      <div  id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
        <div style="height: 85vh; width:auto;" class="carousel-inner">
          <div class="carousel-item active">
            <img src="/static/images/slide/1.jpg" class="d-block w-100" alt="...">
          </div>
          <div class="carousel-item">
            <img src="/static/images/slide/download.jpg" class="d-block w-100" alt="...">
          </div>
          <div class="carousel-item">
            <img src="/static/images/slide/image_processing20180909-4-16tu0lr.jpg" class="d-block w-100" alt="...">
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
    </div>


      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>


  </body>
</html>